# Generated by Django 2.1.4 on 2018-12-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="color_theme",
            field=models.CharField(
                choices=[
                    ("cerulean", "cerulean"),
                    ("cosmo", "cosmo"),
                    ("cyborg", "cyborg"),
                    ("darkly", "darkly (default)"),
                    ("flatly", "flatly"),
                    ("journal", "journal"),
                    ("litera", "litera"),
                    ("lumen", "lumen"),
                    ("lux", "lux"),
                    ("materia", "materia"),
                    ("minty", "minty"),
                    ("pulse", "pulse"),
                    ("pulse", "pulse"),
                    ("sandstone", "sandstone"),
                    ("simplex", "simplex"),
                    ("sketchy", "sketchy"),
                    ("slate", "slate"),
                    ("solar", "solar"),
                    ("spacelab", "spacelab"),
                    ("superhero", "superhero"),
                    ("united", "united"),
                    ("yeti", "yeti"),
                ],
                default="darkly",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="internal_links",
            field=models.BooleanField(default=False),
        ),
    ]
