# Generated by Django 2.1.4 on 2018-12-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0007_readingprogress")]

    operations = [
        migrations.AlterField(
            model_name="readingprogress", name="progress", field=models.IntegerField()
        )
    ]
