# Generated by Django 2.1.4 on 2019-01-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0007_chapter_total_progress"),
        ("profiles", "0009_readingprogress_timestamp"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="readingprogress", unique_together={("chapter", "user")}
        )
    ]
