pipeline:
  django_tests:
    image: python:3.6
    commands:
      - pip install -i $PIPENV_PYPI_MIRROR --trusted-host $PIP_TRUST_MIRROR pipenv
      - pipenv install
      - pipenv run pip freeze > requirements.txt
      - pipenv install --dev
      - pipenv run pip freeze > development.requirements
      - pipenv run python manage.py migrate
      - pipenv run coverage run manage.py test
      - pipenv run coverage report -m
      - pipenv run coverage html
    environment:
      - PIPENV_PYPI_MIRROR=http://192.168.10.11:3141/root/pypi/+simple/
      - PIP_TRUST_MIRROR=192.168.10.11

  publish_requirements:
    image: alpine/git
    commands:
      - sh .ci/add_requirements.sh
    volumes:
      - /root/.ssh:/root/.ssh

  # TODO: publish coverage to webserver

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRES_DB=django

  cache:
    image: redis
