pipeline:

  install_python_dependencies:
    image: python:3.6
    commands:
      - pip install pipenv
      - pipenv install --dev
      - pipenv lock -r > requirements.txt
      - pipenv lock -r --dev > development.requirements
    environment:
      - PIPENV_VENV_IN_PROJECT=true

  run_python_tests:
    image: python:3.6
    commands:
      - pipenv run python manage.py migrate
      - pipenv run coverage run manage.py test
      - pipenv run coverage report -m
      - pipenv run coverage html
    environment:
      - PIPENV_VENV_IN_PROJECT=true

  # publish_requirements:
  #   image: alpine/git
  #   commands:
  #     - sh .ci/add_requirements.sh
  #     - sh .ci/move_coverage.sh
  #   when:
  #     branch: [master, develop, release/*]
  #   volumes:
  #     - /root/.ssh:/root/.ssh
  #     - /srv/coverage/novels:/coverage

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRES_DB=django

  cache:
    image: redis
