pipeline:
  ci:
    image: python:3.6
    commands:
      - pip install pipenv
      - pipenv install
      - pipenv run pip freeze > requirements.txt
      - pipenv install --dev
      - pipenv run pip freeze > development.requirements
      - pipenv run python manage.py migrate
      - pipenv run coverage run manage.py test
      - pipenv run coverage report -m
      - pipenv run coverage html
    environment:
      - PIPENV_PYPI_MIRROR=http://192.168.10.51:3141/root/pypi/+simple/

  ci_commit:
    image: alpine/git
    commands:
      - mkdir -p ~/.ssh && echo "$ssh_key" > ~/.ssh/id_rsa
      - sh .ci/add_requirements.sh
    when:
      branch: master
    secrets: [ ssh_key ]

  # TODO: publish coverage to webserver

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRES_DB=django

  cache:
    image: redis
