pipeline:

  django_tests:
    image: python:3.6
    commands:
      - pip install pipenv
      - pipenv install --dev
      - pipenv lock -r > requirements.txt
      - pipenv lock -r --dev > development.requirements
      - cd src
      - pipenv run python manage.py migrate
      - pipenv run coverage run manage.py test
      - pipenv run coverage report -m
    environment:
      - PIPENV_VENV_IN_PROJECT=true
  code_analysis:
    image: newtmitch/sonar-scanner
    commands:
      - sonar-scanner -Dsonar.projectKey=wohlben_novels -Dsonar.organization=wohlben-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_KEY
    environment:
      SONAR_KEY:
        from_secret: sonar_key


services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRES_DB=django

  cache:
    image: redis
