# Generated by Django 2.1.2 on 2018-10-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("scrapes", "0002_auto_20181011_1936")]

    operations = [migrations.DeleteModel(name="ScrapeGenerators")]
