# Generated by Django 2.1.5 on 2019-02-11 17:33

from django.db import migrations, models


def insert_parser(apps, schema_editor):
    Parser = apps.get_model("scrapes", "Parser")
    Scrapes = apps.get_model("scrapes", "Scrapes")

    parser = Parser.objects.create(name="snek_report", weight=10)

def delete_parser(apps, schema_editor):  # pragma: no cover
    Parser = apps.get_model("scrapes", "Parser")
    Parser.objects.filter(name="snek_report").delete()
    # Scrapes are deleted by cascade


class Migration(migrations.Migration):

    dependencies = [("scrapes", "0011_auto_20181229_1639")]

    operations = [migrations.RunPython(insert_parser, reverse_code=delete_parser)]
