# Generated by Django 2.1.2 on 2018-10-10 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParseLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Parser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapeGenerators",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scrapes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_change", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("http_code", models.IntegerField()),
                (
                    "parser_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scrapes.Parser"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parselog",
            name="parser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scrapes.Parser"
            ),
        ),
        migrations.AddField(
            model_name="parselog",
            name="scrape",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scrapes.Scrapes"
            ),
        ),
    ]
