# Generated by Django 2.1.2 on 2018-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("scrapes", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="scrapes",
            name="http_code",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
