# Generated by Django 2.1.4 on 2018-12-27 13:15

from django.db import migrations, models


def set_scheme(apps, schema_editor):
    Parser = apps.get_model("scrapes", "Parser")
    parsers = {
        "rrl latest": r"https://www.royalroad.com/fictions/latest-updates",
        "rrl chapter": r"https://www.royalroad.com/fiction/\d+/.*?/chapter/\d+/.*?$",
        "rrl novel": r"https://www.royalroad.com/fiction/\d+/(?!.*/)",
    }
    for parser, url_scheme in parsers.items():
        Parser.objects.filter(name=parser).update(url_scheme=url_scheme)


def reset_scheme(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [("scrapes", "0007_parser_weight")]

    operations = [
        migrations.AddField(
            model_name="parser", name="url_scheme", field=models.TextField(blank=True)
        ),
        migrations.RunPython(set_scheme, reverse_code=reset_scheme),
    ]
