# Generated by Django 2.1.4 on 2018-12-28 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("scrapes", "0008_parser_url_scheme")]

    operations = [
        migrations.AddField(
            model_name="parselog",
            name="modified_object",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
