# Generated by Django 2.1.4 on 2018-12-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0009_parselog_modified_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapes',
            options={'permissions': (('force_fetch', 'Allows a User to force a fetch from the source'),)},
        ),
    ]
