# Generated by Django 2.1.4 on 2018-12-26 15:39

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    UserModel = apps.get_model("profiles", "User")
    for user in UserModel.objects.all():
        user.login_token = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [("profiles", "0002_auto_20181226_1106")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_login_token",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="login_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(create_uuid, reverse_code=None),
        migrations.AlterField(
            model_name="user",
            name="login_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
