# Generated by Django 3.0.8 on 2020-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_repair_reading_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oidc_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
