# Generated by Django 3.1 on 2020-08-05 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_user_oidc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingprogress",
            name="progress",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
