# Generated by Django 2.1.2 on 2018-10-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiction',
            name='pic',
        ),
    ]
