# Generated by Django 2.1.2 on 2018-12-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20181216_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiction',
            name='monitored',
        ),
    ]
