# Generated by Django 2.1.4 on 2018-12-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("novels", "0003_remove_fiction_monitored")]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        )
    ]
