# Generated by Django 2.1.4 on 2018-12-28 10:15

from django.db import migrations, models
import django.db.models.deletion


def set_parser(apps, schema_editor):
    Fiction = apps.get_model("novels", "Fiction")
    Parser = apps.get_model("scrapes", "Parser")
    parser = Parser.objects.get(name="rrl novel")
    Fiction.objects.all().update(source=parser)


def reset_parser(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scrapes", "0009_parselog_modified_object"),
        ("novels", "0004_chapter_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiction",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scrapes.Parser",
            ),
        ),
        migrations.RunPython(set_parser, reverse_code=reset_parser),
    ]
