# Generated by Django 2.1.4 on 2018-12-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_fiction_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
    ]
