# Generated by Django 2.1.4 on 2018-12-30 08:36

from django.db import migrations, models
from lxml import html


def set_total_progress(apps, schema_editor):
    Chapter = apps.get_model("novels", "Chapter")
    for chapter in Chapter.objects.exclude(content=None):
        try:
            tree = html.fromstring(chapter.content)
            chapter.total_progress = len(tree.getchildren())
            chapter.save()
        except Exception:
            print(f"failed on {chapter.id}")


def reset_total_progress(apps, schema_editor):
    # whole field will get dropped on migration downgrade, so no need to set null
    pass


class Migration(migrations.Migration):

    dependencies = [("novels", "0006_auto_20181229_1637")]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="total_progress",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(set_total_progress, reverse_code=reset_total_progress),
    ]
