# Generated by Django 2.1.5 on 2019-01-06 15:12

from django.db import migrations, models
import django.db.models.deletion
from lxml import html as _html


def set_word_count(apps, schema_editor):
    Chapter = apps.get_model("novels", "Chapter")
    for chapter in Chapter.objects.exclude(content=None):
        text = _html.fromstring(chapter.content).text_content().strip()
        chapter.word_count = len(text.split())
        chapter.save()


def unset_word_count(apps, schema_editor):
    # irrelevant, as the field gets deleted on reverse
    pass


class Migration(migrations.Migration):

    dependencies = [("novels", "0008_delete_duplicate_fictions")]

    operations = [
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="word_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(set_word_count, reverse_code=unset_word_count),
        migrations.AddField(
            model_name="highlight",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="novels.Chapter"
            ),
        ),
    ]
