# Generated by Django 2.1.5 on 2019-01-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_word_count_and_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('fiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.Fiction')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='characters',
            field=models.ManyToManyField(to='novels.Character'),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('fiction', 'name')},
        ),
    ]
