# Generated by Django 2.1.5 on 2019-02-12 16:44

from django.db import migrations

# the parser manages exactly one novel.... i'd rather not run through an if/else
# on each scrape for something that should occur exactly once ... forever


def insert_novel(apps, schema_editor):
    Parser = apps.get_model("scrapes", "Parser")
    Fiction = apps.get_model("novels", "Fiction")

    parser = Parser.objects.get(name="snek_report")
    Fiction.objects.create(
        source=parser,
        title="The Snake Report",
        author="wercwercwerc",
        url="https://thesnekreport.com/current-chapter",
    )


def remove_novel(apps, schema_editor):
    Fiction = apps.get_model("novels", "Fiction")
    Parser = apps.get_model("scrapes", "Parser")

    parser = Parser.objects.get(name="snek_report")
    Fiction.objects.filter(source=parser).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0010_added_characters"),
        ("scrapes", "0012_insert_snakey_parser"),
    ]

    operations = [migrations.RunPython(insert_novel, reverse_code=remove_novel)]
