# Generated by Django 3.0.8 on 2020-07-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0011_added_snake_report_novel"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chapter", index=models.Index(fields=["-published"], name="novels_chap_publish_96e98b_idx"),
        ),
    ]
