# Generated by Django 3.0.8 on 2020-08-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0014_fiction_author_obj"),
    ]

    operations = [
        migrations.RemoveField(model_name="fiction", name="author",),
        migrations.RenameField(model_name="fiction", old_name="author_obj", new_name="author",),
    ]
