# Generated by Django 3.1 on 2020-08-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0015_remove_fiction_author"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="chapter", unique_together={("remote_id", "fiction")},),
    ]
