# Generated by Django 3.1 on 2020-08-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapes", "0014_auto_20200806_2313"),
        ("novels", "0016_auto_20200819_2057"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="fiction", unique_together={("remote_id", "source")},),
    ]
